// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc8mW4XWYAeWxYlWOJ6js4ncIheWuWtD0',
    appId: '1:218147066491:web:338796ec84ca67ed0388de',
    messagingSenderId: '218147066491',
    projectId: 'ratting-app-34a8e',
    authDomain: 'ratting-app-34a8e.firebaseapp.com',
    storageBucket: 'ratting-app-34a8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9p8Bhu3XfI8CjkupSTtVf4mZJOQmr0aI',
    appId: '1:218147066491:android:f797e15aab7f9c7f0388de',
    messagingSenderId: '218147066491',
    projectId: 'ratting-app-34a8e',
    storageBucket: 'ratting-app-34a8e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc8mW4XWYAeWxYlWOJ6js4ncIheWuWtD0',
    appId: '1:218147066491:web:338796ec84ca67ed0388de',
    messagingSenderId: '218147066491',
    projectId: 'ratting-app-34a8e',
    authDomain: 'ratting-app-34a8e.firebaseapp.com',
    storageBucket: 'ratting-app-34a8e.firebasestorage.app',
  );
}
